### ISSUE TITLE
AttributeError: module 'gzip' has no attribute 'BadGzipFile'

### ISSUE THREAD

**Issue by Dvev** [radomirbosak/duden#132]
Hey i got a problem with simply printing the name of a word. I dont know how else i can described it :D 
![Bild_2021-05-01_160005](https://user-images.githubusercontent.com/54837624/116784770-4b4bb080-aa96-11eb-88ad-9b6b8175b74f.png)
This is the Full error and thats what im trying to do :
![Bild_2021-05-01_160104](https://user-images.githubusercontent.com/54837624/116784793-6e766000-aa96-11eb-95bc-698d65d4e617.png) Please ignore the comments there ^^ im just trying to get this module to work 
Thank you beforehand

**Comment by radomirbosak** [comment]
Sorry, this is my fault for using [gzip.BadGzipFile exception](https://docs.python.org/3/library/gzip.html#gzip.BadGzipFile) which is supported only since python3.8 . I removed it and updated the package in master branch and also pypi.

This should update your package to the fixed version `0.14.4`
```
pip3 install --user --upgrade duden
```
Please let me know if there's something else not working.

**Comment by radomirbosak** [comment]
I need to start testing for multiple python versions
https://github.com/radomirbosak/duden/issues/134

**Comment by Dvev** [comment]
Hey im switched my project on python 3.8 now and it works now!
It does work with 3.7 too just saying :D 
Ty alot tho ^^
